// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTable: typeof import('./components/ui/table/BaseTable.vue')['default']
    BaseTableItem: typeof import('./components/ui/table/BaseTableItem.vue')['default']
    BaseTableRow: typeof import('./components/ui/table/BaseTableRow.vue')['default']
    BaseThemeLocale: typeof import('./components/ui/BaseThemeLocale.vue')['default']
    BaseThemeToggle: typeof import('./components/ui/BaseThemeToggle.vue')['default']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    Markdown: typeof import('./components/Markdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('@headlessui/vue')['Switch']
    TheNavbar: typeof import('./components/layout/TheNavbar.vue')['default']
  }
}

export {}
